-- MySQL Workbench Synchronization
-- Generated: 2021-11-26 16:54
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: lorenzo

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE TABLE IF NOT EXISTS `cnf_spid`.`spid_users` (
    `spid_row_id` INT(11) NOT NULL AUTO_INCREMENT,
    `spid_login_res_id` VARCHAR(255) NOT NULL,
    `cf` VARCHAR(45) NOT NULL,
    `idp` VARCHAR(45) NOT NULL,
    `spid_userscol` VARCHAR(255) NOT NULL,
    `insert_datetime` VARCHAR(45) NOT NULL,
    `expire_datetime` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`spid_row_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
